### ISSUE TITLE
Pkg: Fix the Number input spinner arrows

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1142]
### Problem
![screen shot 2017-10-18 at 14 50 41](https://user-images.githubusercontent.com/22662903/31719459-d5abf1fe-b413-11e7-8567-a8b0201e4470.png)

The arrows of the spinner are too not centered in the button. See design
https://app.zeplin.io/project/598cce4ab8aced8f15a420a1/screen/598ccec37590e0a1313bb633

**Comment by xak** [comment]
Fixed with #1160

**Comment by joseegm** [comment]
We still have some issues here

![screen shot 2017-10-24 at 11 32 33](https://user-images.githubusercontent.com/22662903/31935460-29f4bfb2-b8af-11e7-9100-59402506ab39.png)

The border is now a little round and the chevron are still not quite vertically in the middle of the button.
![screen shot 2017-10-24 at 11 33 50](https://user-images.githubusercontent.com/22662903/31935528-5eb05d56-b8af-11e7-92b2-ca8025deed76.png)
